version: '3.8'

services:
  mysql-db:
#    platform: linux/amd64
    container_name: mysql-db
    image: mysql:8.0.33
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql8
    environment:
      MYSQL_DATABASE: lastminute
      MYSQL_USER: root
      MYSQL_PASSWORD: p@ssword
      MYSQL_ROOT_PASSWORD: p@ssword
    networks:
      - spring-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 5s
      timeout: 3s
      retries: 20
    restart: always

  lastminute-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-db
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/lastminute?
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: p@ssword
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
#      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mysql-data: