server:
  port: 8080
spring:
  config:
    import:
      - classpath:/cloud.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql-db:3314/lastminute?
#    username: root
#    password: p@ssword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    org:
      hibernate:
        SQL: debug

jwt:
  secret: "Jmm8XCpzXdRD5VrWvH0y4zBA6hWv9r28173HmuBuUt4="