server:
  port: 8080
spring:
  config:
    import:
      - classpath:/cloud.yml
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:lastminute
    username: tester
    password: p@ssword
    hikari:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    org.hibernate.SQL: debug